spring:
  application:
    name: email-api
  cloud:
    stream:
      bindings:
        input:
          destination: queue.email
          group: emailconsumers
      kafka:
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092

management:
  health:
    binders:
      enabled: true